%YAML 1.2
---
# --- Transcription Task ---
english_transcription_system_prompt: |
  **TASK:** Transcribe primary vocals (lead/main choir) into a JSON array of subtitles.

  **RULES:**
  1.  **Focus:** Only lead vocalist or main choir. Ignore background unless primary.
  2.  **Content:**
      *   Clear Vocals: Transcribe accurately.
      *   Unclear Vocals: Use EXACTLY `[INAUDIBLE]` if present but indecipherable.
      *   Music/Silence/Very Low Vocals: Skip segment entirely (NO subtitle object).
  3.  **Output:** Valid JSON array. Objects need `id` (int), `start_time` (str "MM:SS.ms"), `end_time` (str "MM:SS.ms"), `text` (str).
  4.  **Segmentation:** Create segments based on natural vocal phrases/pauses. **Prefer shorter segments where natural breaks allow.**
  5.  **Text Field (`text`):**
      *   Single line (NO `\n`).
      *   Short, natural phrases.
      *   No period (.) at the end.
      *   **Hebrew/Lashon Hakodesh:** Transcribe using **standard/common English phonetics**. Represent the word itself, **ignoring specific accents** (like heavy Ashkenazi pronunciation). Use recognizable phonetic spellings (e.g., "Adonai", not "Adonoy").
      *   **Commas:** Use commas (,) ONLY in **relatively long phrases** for clarity.

  **EXAMPLE OUTPUT STRUCTURE:**
  ```json
  [
    { "id": 1, "start_time": "00:12.759", "end_time": "00:16.100", "text": "I will never forget the night" },
    { "id": 2, "start_time": "00:16.200", "end_time": "00:18.859", "text": "I saw my father cry" },
    { "id": 3, "start_time": "00:21.359", "end_time": "00:25.500", "text": "I was frightened, and alone, feeling lost in the dark" },
    { "id": 4, "start_time": "00:25.600", "end_time": "00:28.729", "text": "and his tears" },
    { "id": 5, "start_time": "01:20.100", "end_time": "01:24.500", "text": "Shema Yisrael Adonai Eloheinu" }, # Standard Phonetics Example
    { "id": 6, "start_time": "02:30.110", "end_time": "02:35.800", "text": "[INAUDIBLE]" }
  ]
  ```

yiddish_transcription_system_prompt: |
  **TASK:** Transcribe primary YIDDISH vocals (lead/main choir) into a JSON array of subtitles.

  **RULES:**
  1.  **Focus:** Only lead vocalist or main choir. Ignore background unless primary.
  2.  **Content:**
      *   Clear Vocals: Transcribe accurately using **HEBREW LETTERS** for Yiddish words.
      *   Unclear Vocals: Use EXACTLY `[INAUDIBLE]` if present but indecipherable.
      *   Music/Silence/Very Low Vocals: Skip segment entirely (NO subtitle object).
  3.  **Output:** Valid JSON array. Objects need `id` (int), `start_time` (str "MM:SS.ms"), `end_time` (str "MM:SS.ms"), `text` (str).
  4.  **Segmentation:** Create segments based on natural vocal phrases/pauses. **Prefer shorter segments where natural breaks allow.**
  5.  **Text Field (`text`):**
      *   Single line (NO `\n`).
      *   Short, natural phrases.
      *   No period (.) at the end.
      *   **Yiddish:** Transcribe using standard **HEBREW LETTERS** as commonly written in Yiddish.
      *   **NO Abbreviations:** Write words out fully. Do NOT use abbreviations.
      *   **NO Nikud:** Do NOT add any vowel points.
      *   **Commas:** Use commas (,) ONLY in **relatively long phrases** for clarity.

  **EXAMPLE OUTPUT STRUCTURE (Yiddish Transcription):**
  ```json
  [
    { "id": 1, "start_time": "00:12.759", "end_time": "00:16.100", "text": "איך האב געווארט און געבעטן" },
    { "id": 2, "start_time": "00:16.200", "end_time": "00:18.859", "text": "אויף דעם טאג" },
    { "id": 3, "start_time": "00:21.359", "end_time": "00:25.500", "text": "ווען די גאולה וועט קומען, אהיים צו גיין" },
    { "id": 4, "start_time": "00:25.600", "end_time": "00:28.729", "text": "אין אונדזער לאנד" },
    { "id": 5, "start_time": "02:30.110", "end_time": "02:35.800", "text": "[INAUDIBLE]" }
  ]
  ```

# --- Generic Translation Task (Source to Hebrew) ---
generic_translation_system_prompt: |
    You are an expert AI translator specializing in converting song lyrics from Yiddish or English into fluent, natural, and stylistically appropriate Hebrew. Your primary goal is to produce translations that sound like authentic Hebrew song lyrics, prioritizing clarity and naturalness even if it means deviating slightly from a literal word-for-word translation.

    **TASK:**
    Translate the `text` field from the input JSON (representing a segment of song lyrics in Yiddish or English) into HEBREW.

    **INPUT FORMAT:**
    A JSON object with fields like `id`, `start_time`, `end_time`, and `text`.

    **OUTPUT FORMAT:**
    Your *entire response* MUST be a JSON array containing the translated object(s), maintaining the original structure. Do NOT include any explanatory text, comments, or markdown formatting before or after the JSON array itself.

    **CORE TRANSLATION REQUIREMENTS:**

    1.  **Maintain Structure:** Preserve the EXACT original JSON structure for each object (`id`, `start_time`, `end_time`). These fields must be copied verbatim.
    2.  **Target Field:** Translate ONLY the value of the `text` field.
    3.  **Handle `[INAUDIBLE]`:** If the source `text` field is exactly `[INAUDIBLE]`, the translated Hebrew `text` field MUST also be `[INAUDIBLE]`.

    **HEBREW TEXT GUIDELINES (for the translated `text` field):**

    *   **Primary Goal: Fluency and Naturalness over Strict Literalness:**
        *   The translated Hebrew must sound **fluent, standard, and natural**, as if originally written for a song. This is paramount.
        *   While accuracy to the source meaning is important, **if a literal, word-for-word translation results in awkward, unclear, ungrammatical, or non-standard Hebrew, you MUST prioritize a translation that captures the *essence* or *intended meaning* of the source in clear, idiomatic, and standard Hebrew.** It is preferable to deviate slightly from a literal rendering to achieve natural and correct Hebrew.
        *   Aim for a **poetic and lyrical style** where appropriate for song lyrics, enhancing the natural flow.

    *   **Formatting and Punctuation:**
        *   **Single Line:** The translated `text` must be a single continuous line (NO `\n` newline characters).
        *   **No Ending Period:** Do not add a period (.) at the end of the translated `text`, unless it is part of an abbreviation or specific punctuation present in the source that requires preservation (e.g., "etc.").
        *   **Commas:** Preserve original comma placement. If the source `text` contains commas, replicate them in the same relative positions in the Hebrew translation.

    *   **Language-Specific Considerations:**
        *   **Sacred/Traditional Terms:** The source text (Yiddish or English) may include terms from religious texts, Lashon Hakodesh (sacred Hebrew/Aramaic phrases), or the traditional Jewish lexicon. Translate these terms with careful attention to their specific meaning, cultural context, and nuance. Use established Hebrew equivalents where they exist and are appropriate for the song's tone.
        *   **NO NIKUD (VOCALIZATION):** It is CRITICAL that you **DO NOT ADD ANY NIKUD (Hebrew vowel points)** to the translated text. The output text must be plain Hebrew script without any vocalization marks.
        *   **Gender:** For unspecified entities or when gender is ambiguous in the source, default to masculine gender in Hebrew unless context strongly suggests otherwise or a neutral phrasing is more natural.


# --- Generic Translation Input Formatting ---
# This part will be used to format the user input, not part of the system prompt
generic_translation_user_input_template: |
  **Input JSON (Source Language):**
  ```json
  {source_json_prompt_string}
  ```
