%YAML 1.2
---
# Instructions for Gemini API: Audio Transcription and Translation

# --- Transcription Task (Concise) ---
transcription_prompt: |
  **TASK:** Transcribe primary vocals (lead/main choir) into a JSON array of subtitles.

  **RULES:**
  1.  **Focus:** Only lead vocalist or main choir. Ignore background unless primary.
  2.  **Content:**
      *   Clear Vocals: Transcribe accurately.
      *   Unclear Vocals: Use EXACTLY `[INAUDIBLE]` if present but indecipherable.
      *   Music/Silence/Very Low Vocals: Skip segment entirely (NO subtitle object).
  3.  **Output:** Valid JSON array. Objects need `id` (int), `start_time` (str "MM:SS.ms"), `end_time` (str "MM:SS.ms"), `text` (str).
  4.  **Segmentation:** Create segments based on natural vocal phrases/pauses. **Prefer shorter segments where natural breaks allow.**
  5.  **Text Field (`text`):**
      *   Single line (NO `\n`).
      *   Short, natural phrases.
      *   No period (.) at the end.
      *   **Hebrew/Lashon Hakodesh:** Transcribe **accurately** using English phonetics.
      *   **Commas:** Use commas (,) ONLY in **relatively long phrases** for clarity.

  **EXAMPLE OUTPUT STRUCTURE:**
  ```json
  [
    { "id": 1, "start_time": "00:12.759", "end_time": "00:16.100", "text": "I will never forget the night" }, # No comma needed here
    { "id": 2, "start_time": "00:16.200", "end_time": "00:18.859", "text": "I saw my father cry" },
    { "id": 3, "start_time": "00:21.359", "end_time": "00:25.500", "text": "I was frightened, and alone, feeling lost in the dark" }, # Comma in longer phrase
    { "id": 4, "start_time": "00:25.600", "end_time": "00:28.729", "text": "and his tears" },
    { "id": 5, "start_time": "01:20.100", "end_time": "01:24.500", "text": "Shema Yisrael Adonai Eloheinu" }, # Phonetic, no comma needed
    { "id": 6, "start_time": "02:30.110", "end_time": "02:35.800", "text": "[INAUDIBLE]" }
  ]
  ```

# --- Translation Task ---
translation_prompt_template: |
  **TASK:** Translate the `text` field of the input English JSON into natural-sounding Hebrew.

  **INPUT:** English JSON array (provided below).

  **CORE REQUIREMENTS:**
  1.  **Structure:** Maintain EXACT original JSON structure (`id`, `start_time`, `end_time`).
  2.  **Target:** Translate ONLY the `text` field value.
  3.  **`[INAUDIBLE]`:** If English `text` is `[INAUDIBLE]`, Hebrew `text` MUST be `[INAUDIBLE]`.
  4.  **Output:** Translated JSON Array ONLY.

  **HEBREW TEXT RULES (Translated `text`):**
  *   Natural Hebrew, single line (NO `\n`).
  *   No period (.) at the end.
  *   **Commas:** Use commas (,) **exactly as they appear in the original English `text`**.
  *   No Nikud.
  *   Default to masculine gender for unspecified entities.

  **Original English JSON:**
  ```json
  {english_json_prompt_string}
  ```